service: rust-lambda-serverless 

provider:
  name: aws
  runtime: nodejs16.x

functions:
  rust_serverless_example_wasm:
    handler: pkg/rust_serverless_example.handler
    events:
     - http:
         path: /
         method: get

plugins:
  - serverless-offline